Repository osama1998H/kalima, pull requests merged in 2024-07, with the labels that each got.

#30 Result page
  kalima/kalima/doctype/applicant_student/applicant_student.json
  kalima/kalima/doctype/assessment_criteria/assessment_criteria.js
  kalima/kalima/doctype/assessment_criteria/assessment_criteria.json
  kalima/kalima/doctype/assessment_criteria/test_assessment_criteria.py
  kalima/kalima/doctype/assessment_criteria_table/assessment_criteria_table.json
  kalima/kalima/doctype/assessment_criteria_table/assessment_criteria_table.py
  kalima/kalima/doctype/assessment_plan/__init__.py
  kalima/kalima/doctype/assessment_plan/assessment_plan.js
  kalima/kalima/doctype/assessment_plan/assessment_plan.json
  kalima/kalima/doctype/assignment_marks/__init__.py
  kalima/kalima/doctype/assignment_marks/assignment_marks.json
  kalima/kalima/doctype/assignment_marks/assignment_marks.py
  kalima/kalima/doctype/assignments_and_tasks/assignments_and_tasks.js
  kalima/kalima/doctype/assignments_and_tasks/assignments_and_tasks.json
  kalima/kalima/doctype/assignments_and_tasks/assignments_and_tasks.py
  kalima/kalima/doctype/department_tuition_fee/__init__.py
  kalima/kalima/doctype/department_tuition_fee/department_tuition_fee.json
  kalima/kalima/doctype/department_tuition_fee/department_tuition_fee.py
  kalima/kalima/doctype/department_tuition_fee/test_department_tuition_fee.py
  kalima/kalima/doctype/installment/__init__.py
  kalima/kalima/doctype/installment/installment.js
  kalima/kalima/doctype/installment/installment.json
  kalima/kalima/doctype/installment/installment.py
  kalima/kalima/doctype/installment/test_installment.py
  kalima/kalima/doctype/province/__init__.py
  kalima/kalima/doctype/province/province.js
  kalima/kalima/doctype/province/province.json
  kalima/kalima/doctype/province/province.py
  kalima/kalima/doctype/province/test_province.py
  kalima/kalima/doctype/research/__init__.py
  kalima/kalima/doctype/research/research.js
  kalima/kalima/doctype/research/research.json
  kalima/kalima/doctype/research/research.py
  kalima/kalima/doctype/research/test_research.py
  kalima/kalima/doctype/return_book/__init__.py
  kalima/kalima/doctype/return_book/return_book.js
  kalima/kalima/doctype/return_book/return_book.json
  kalima/kalima/doctype/return_book/return_book.py
  kalima/kalima/doctype/return_book/test_return_book.py
  kalima/kalima/doctype/student/student.json
  kalima/kalima/doctype/student_result_log/student_result_log.json
  kalima/kalima/page/class_managment/class_managment.js
  kalima/kalima/workspace/kalima/kalima.json
  kalima/utils/utils.py
Labels: size/XXL

#31 Result page
  kalima/kalima/doctype/activity/activity.js
  kalima/kalima/doctype/activity/activity.json
  kalima/kalima/doctype/activity_announcement/activity_announcement.js
  kalima/kalima/doctype/activity_announcement/activity_announcement.json
  kalima/kalima/doctype/activity_certificate/activity_certificate.json
  kalima/kalima/doctype/activity_coordination/activity_coordination.json
  kalima/kalima/doctype/activity_participant/__init__.py
  kalima/kalima/doctype/activity_participant/activity_participant.js
  kalima/kalima/doctype/activity_participant/activity_participant.json
  kalima/kalima/doctype/activity_participant/activity_participant.py
  kalima/kalima/doctype/activity_participant/test_activity_participant.py
  kalima/kalima/doctype/activity_request/activity_request.json
  kalima/kalima/doctype/applicant_student/applicant_student.js
  kalima/kalima/doctype/applicant_student/applicant_student.json
  kalima/kalima/doctype/applicant_student/applicant_student.py
  kalima/kalima/doctype/dormitory/dormitory.js
  kalima/kalima/doctype/dormitory/dormitory.json
  kalima/kalima/doctype/dormitory/dormitory.py
  kalima/kalima/doctype/exam_hall_distribution/exam_hall_distribution.json
  kalima/kalima/doctype/exam_schedule/exam_schedule.json
  kalima/kalima/doctype/student/student.js
  kalima/kalima/doctype/student/student.json
  kalima/kalima/doctype/student/student.py
  kalima/kalima/doctype/students_fees/students_fees.js
  kalima/kalima/doctype/transfer/transfer.json
  kalima/kalima/doctype/transfer/transfer.py
  kalima/kalima/doctype/week_day/week_day.json
  kalima/kalima/page/student_portal/student_portal.js
  kalima/kalima/web_form/student_application_form/student_application_form.json
  kalima/utils/utils.py
Labels: size/XL

#33 edit
  kalima/kalima/doctype/faculty_department/faculty_department.json
Labels: size/XS

#34 fix
  kalima/kalima/doctype/presented_module/presented_module.json
Labels: size/S

#35 get student fix
  kalima/kalima/page/student_portal/student_portal.js
Labels: size/XS

#37 July 6
  kalima/fixtures/week_day.json
  kalima/hooks.py
  kalima/kalima/doctype/activity/activity.js
  kalima/kalima/doctype/applicant_student/applicant_student.py
  kalima/kalima/doctype/book/book.json
  kalima/kalima/doctype/book_category/book_category.json
  kalima/kalima/doctype/class_timetable/class_timetable.json
  kalima/kalima/doctype/exam_hall_distribution/exam_hall_distribution.py
  kalima/kalima/doctype/incoming/incoming.json
  kalima/kalima/doctype/lend_book/lend_book.js
  kalima/kalima/doctype/lend_book/lend_book.json
  kalima/kalima/doctype/outgoing/outgoing.js
  kalima/kalima/doctype/student/student.json
  kalima/kalima/doctype/student/student.py
  kalima/kalima/doctype/students_fees/students_fees.js
  kalima/kalima/doctype/transfer/transfer.py
  kalima/kalima/page/student_portal/student_portal.js
Labels: size/L

#38 fix naming
  kalima/kalima/doctype/activity/activity.json
  kalima/kalima/doctype/activity_announcement/activity_announcement.json
  kalima/kalima/doctype/activity_certificate/activity_certificate.json
  kalima/kalima/doctype/activity_coordination/activity_coordination.json
  kalima/kalima/doctype/activity_request/activity_request.json
  kalima/kalima/doctype/book/book.json
  kalima/kalima/doctype/dormitory/dormitory.json
  kalima/kalima/doctype/exam_hall_distribution/exam_hall_distribution.json
  kalima/kalima/doctype/exam_questions/exam_questions.json
  kalima/kalima/doctype/exam_schedule/exam_schedule.json
  kalima/kalima/doctype/fining_system/fining_system.json
  kalima/kalima/doctype/incoming/incoming.json
  kalima/kalima/doctype/question_prototype/question_prototype.json
  kalima/kalima/doctype/students_fees/students_fees.json
  kalima/kalima/doctype/transfer/transfer.json
Labels: size/L

#36 Page Fix
  kalima/fixtures/week_day.json
  kalima/hooks.py
  kalima/kalima/doctype/activity/activity.js
  kalima/kalima/doctype/activity/activity.json
  kalima/kalima/doctype/activity_announcement/activity_announcement.json
  kalima/kalima/doctype/activity_certificate/activity_certificate.json
  kalima/kalima/doctype/activity_coordination/activity_coordination.json
  kalima/kalima/doctype/activity_request/activity_request.json
  kalima/kalima/doctype/applicant_student/applicant_student.py
  kalima/kalima/doctype/book/book.json
  kalima/kalima/doctype/book_category/book_category.json
  kalima/kalima/doctype/class_timetable/class_timetable.json
  kalima/kalima/doctype/dormitory/dormitory.json
  kalima/kalima/doctype/exam_hall_distribution/exam_hall_distribution.json
  kalima/kalima/doctype/exam_hall_distribution/exam_hall_distribution.py
  kalima/kalima/doctype/exam_questions/exam_questions.json
  kalima/kalima/doctype/exam_schedule/exam_schedule.json
  kalima/kalima/doctype/fining_system/fining_system.json
  kalima/kalima/doctype/incoming/incoming.json
  kalima/kalima/doctype/lend_book/lend_book.js
  kalima/kalima/doctype/lend_book/lend_book.json
  kalima/kalima/doctype/outgoing/outgoing.js
  kalima/kalima/doctype/question_prototype/question_prototype.json
  kalima/kalima/doctype/student/student.json
  kalima/kalima/doctype/student/student.py
  kalima/kalima/doctype/students_fees/students_fees.js
  kalima/kalima/doctype/students_fees/students_fees.json
  kalima/kalima/doctype/transfer/transfer.json
  kalima/kalima/doctype/transfer/transfer.py
  kalima/kalima/page/student_portal/student_portal.js
  kalima/kalima/page/student_result_sheet_1/__init__.py
  kalima/kalima/page/student_result_sheet_1/student_result_sheet_1.js
  kalima/kalima/page/student_result_sheet_1/student_result_sheet_1.json
  kalima/utils/utils.py
Labels: size/XL

#39 chnage verion number
  kalima/__init__.py
Labels: size/XS

#40 update app version
  kalima/__init__.py
Labels: size/XS

#42 grad date
  kalima/kalima/doctype/student/student.json
  kalima/kalima/web_form/student_application_form/student_application_form.json
Labels: size/S

#43 workspace
  kalima/kalima/workspace/e1ums/e1ums.json
  kalima/kalima/workspace/kalima/kalima.json
Labels: size/XXL

#44 workspace rename
  kalima/kalima/workspace/A1UMS/A1UMS.json
  kalima/kalima/workspace/A1UMS/A1UMS.jsonZone.Identifier
Labels: size/S

#45 Part 3
  kalima/fixtures/role.json
  kalima/kalima/doctype/assignments_and_tasks/assignments_and_tasks.json
  kalima/kalima/doctype/class_continuous_exam/class_continuous_exam.json
  kalima/kalima/doctype/class_session/class_session.json
  kalima/kalima/doctype/class_timetable/class_timetable.json
  kalima/kalima/page/class_managment/class_managment.js
  kalima/kalima/page/student_portal/student_portal.js
  kalima/utils/utils.py
Labels: size/XL

#47 update workspace name
  kalima/kalima/workspace/A1UMS/A1UMS.jsonZone.Identifier
  kalima/kalima/workspace/a1erp/a1erp.json
Labels: size/S

#50 Part 4
  kalima/kalima/doctype/attednance/attednance.json
  kalima/kalima/doctype/class_timetable/class_timetable.json
  kalima/kalima/doctype/student_attendance_entry/student_attendance_entry.json
  kalima/kalima/page/class_managment/class_managment.js
  kalima/kalima/page/student_portal/student_portal.js
  kalima/kalima/report/students_absence/__init__.py
  kalima/kalima/report/students_absence/students_absence.js
  kalima/kalima/report/students_absence/students_absence.json
  kalima/kalima/report/students_absence/students_absence.py
  kalima/utils/utils.py
Labels: size/L

#51 Develop
  kalima/kalima/doctype/attednance/attednance.json
  kalima/kalima/doctype/class_timetable/class_timetable.json
  kalima/kalima/doctype/student_attendance_entry/student_attendance_entry.json
  kalima/kalima/page/class_managment/class_managment.js
  kalima/kalima/page/student_portal/student_portal.js
  kalima/kalima/report/students_absence/__init__.py
  kalima/kalima/report/students_absence/students_absence.js
  kalima/kalima/report/students_absence/students_absence.json
  kalima/kalima/report/students_absence/students_absence.py
  kalima/utils/utils.py
Labels: size/L

#52 attendance report
  kalima/kalima/doctype/activity/activity.js
  kalima/kalima/doctype/activity/activity.json
  kalima/kalima/doctype/activity_announcement/activity_announcement.js
  kalima/kalima/doctype/activity_announcement/activity_announcement.json
  kalima/kalima/doctype/activity_certificate/activity_certificate.js
  kalima/kalima/doctype/activity_certificate/activity_certificate.json
  kalima/kalima/doctype/applicant_student/applicant_student.js
  kalima/kalima/doctype/applicant_student/applicant_student.json
  kalima/kalima/doctype/applicant_student/applicant_student.py
  kalima/kalima/doctype/book/book.json
  kalima/kalima/doctype/book_category/book_category.json
  kalima/kalima/doctype/books_tags/__init__.py
  kalima/kalima/doctype/books_tags/books_tags.json
  kalima/kalima/doctype/books_tags/books_tags.py
  kalima/kalima/doctype/class/class.json
  kalima/kalima/doctype/complaints/complaints.json
  kalima/kalima/doctype/department_module/department_module.json
  kalima/kalima/doctype/exam_questions/exam_questions.json
  kalima/kalima/doctype/faculty_department/faculty_department.js
  kalima/kalima/doctype/faculty_department/faculty_department.json
  kalima/kalima/doctype/faculty_department/test_faculty_department.py
  kalima/kalima/doctype/group_class/group_class.json
  kalima/kalima/doctype/group_class/group_class.py
  kalima/kalima/doctype/group_class/test_group_class.py
  kalima/kalima/doctype/incoming/incoming.js
  kalima/kalima/doctype/incoming/incoming.json
  kalima/kalima/doctype/kalima_settings/kalima_settings.json
  kalima/kalima/doctype/lend_book/lend_book.js
  kalima/kalima/doctype/lend_book/lend_book.json
  kalima/kalima/doctype/library/library.json
  kalima/kalima/doctype/ministry_exam_results/ministry_exam_results.json
  kalima/kalima/doctype/outgoing/outgoing.js
  kalima/kalima/doctype/outgoing/outgoing.json
  kalima/kalima/doctype/presented_department/__init__.py
  kalima/kalima/doctype/presented_department/presented_department.js
  kalima/kalima/doctype/presented_department/presented_department.json
  kalima/kalima/doctype/presented_department/presented_department.py
  kalima/kalima/doctype/presented_department/test_presented_department.py
  kalima/kalima/doctype/presented_departments_table/__init__.py
  kalima/kalima/doctype/presented_departments_table/presented_departments_table.json
  kalima/kalima/doctype/presented_departments_table/presented_departments_table.py
  kalima/kalima/doctype/presented_module/presented_module.json
  kalima/kalima/doctype/student/student.json
  kalima/kalima/doctype/student/student.py
  kalima/kalima/page/class_distribution_t/class_distribution_t.js
  kalima/kalima/page/class_managment/class_managment.html
  kalima/kalima/page/class_managment/class_managment.js
  kalima/kalima/report/students_absence/students_absence.py
  kalima/kalima/web_form/activity_request/__init__.py
  kalima/kalima/web_form/activity_request/activity_request.js
  kalima/kalima/web_form/activity_request/activity_request.json
  kalima/kalima/web_form/activity_request/activity_request.py
  kalima/kalima/workspace/a1ums/a1ums.json
  kalima/kalima/workspace/teacher/teacher.json
  kalima/public/group_class.js
  kalima/utils/group_class.py
  kalima/utils/group_class_old.py
Labels: size/XXL

#53 Develop
  kalima/kalima/doctype/activity/activity.js
  kalima/kalima/doctype/activity/activity.json
  kalima/kalima/doctype/activity_announcement/activity_announcement.js
  kalima/kalima/doctype/activity_announcement/activity_announcement.json
  kalima/kalima/doctype/activity_certificate/activity_certificate.js
  kalima/kalima/doctype/activity_certificate/activity_certificate.json
  kalima/kalima/doctype/applicant_student/applicant_student.js
  kalima/kalima/doctype/applicant_student/applicant_student.json
  kalima/kalima/doctype/applicant_student/applicant_student.py
  kalima/kalima/doctype/book/book.json
  kalima/kalima/doctype/book_category/book_category.json
  kalima/kalima/doctype/books_tags/__init__.py
  kalima/kalima/doctype/books_tags/books_tags.json
  kalima/kalima/doctype/books_tags/books_tags.py
  kalima/kalima/doctype/class/class.json
  kalima/kalima/doctype/complaints/complaints.json
  kalima/kalima/doctype/department_module/department_module.json
  kalima/kalima/doctype/exam_questions/exam_questions.json
  kalima/kalima/doctype/faculty_department/faculty_department.js
  kalima/kalima/doctype/faculty_department/faculty_department.json
  kalima/kalima/doctype/faculty_department/test_faculty_department.py
  kalima/kalima/doctype/group_class/group_class.json
  kalima/kalima/doctype/group_class/group_class.py
  kalima/kalima/doctype/group_class/test_group_class.py
  kalima/kalima/doctype/incoming/incoming.js
  kalima/kalima/doctype/incoming/incoming.json
  kalima/kalima/doctype/kalima_settings/kalima_settings.json
  kalima/kalima/doctype/lend_book/lend_book.js
  kalima/kalima/doctype/lend_book/lend_book.json
  kalima/kalima/doctype/library/library.json
  kalima/kalima/doctype/ministry_exam_results/ministry_exam_results.json
  kalima/kalima/doctype/outgoing/outgoing.js
  kalima/kalima/doctype/outgoing/outgoing.json
  kalima/kalima/doctype/presented_department/__init__.py
  kalima/kalima/doctype/presented_department/presented_department.js
  kalima/kalima/doctype/presented_department/presented_department.json
  kalima/kalima/doctype/presented_department/presented_department.py
  kalima/kalima/doctype/presented_department/test_presented_department.py
  kalima/kalima/doctype/presented_departments_table/__init__.py
  kalima/kalima/doctype/presented_departments_table/presented_departments_table.json
  kalima/kalima/doctype/presented_departments_table/presented_departments_table.py
  kalima/kalima/doctype/presented_module/presented_module.json
  kalima/kalima/doctype/student/student.json
  kalima/kalima/doctype/student/student.py
  kalima/kalima/page/class_distribution_t/class_distribution_t.js
  kalima/kalima/page/class_managment/class_managment.html
  kalima/kalima/page/class_managment/class_managment.js
  kalima/kalima/report/students_absence/students_absence.py
  kalima/kalima/web_form/activity_request/__init__.py
  kalima/kalima/web_form/activity_request/activity_request.js
  kalima/kalima/web_form/activity_request/activity_request.json
  kalima/kalima/web_form/activity_request/activity_request.py
  kalima/kalima/workspace/a1ums/a1ums.json
  kalima/kalima/workspace/teacher/teacher.json
  kalima/public/group_class.js
  kalima/utils/group_class.py
  kalima/utils/group_class_old.py
Labels: size/XXL

#56 page tries
  kalima/kalima/page/master_sheet/master_sheet.py
Labels: size/L

#57 Develop
  kalima/kalima/page/master_sheet/master_sheet.py
Labels: size/L

#58 notification fix
  kalima/fixtures/notification.json
  kalima/kalima/notification/__init__.py
  kalima/kalima/notification/incoming_document/__init__.py
  kalima/kalima/notification/incoming_document/incoming_document.json
  kalima/kalima/notification/incoming_document/incoming_document.md
  kalima/kalima/notification/incoming_document/incoming_document.py
  kalima/kalima/notification/incoming_document___{{_doc.name_}}/__init__.py
  kalima/kalima/notification/incoming_document___{{_doc.name_}}/incoming_document___{{_doc.name_}}.json
  kalima/kalima/notification/incoming_document___{{_doc.name_}}/incoming_document___{{_doc.name_}}.md
  kalima/kalima/notification/incoming_document___{{_doc.name_}}/incoming_document___{{_doc.name_}}.py
Labels: size/M

#59 Develop
  kalima/fixtures/notification.json
  kalima/kalima/notification/__init__.py
  kalima/kalima/notification/incoming_document/__init__.py
  kalima/kalima/notification/incoming_document/incoming_document.json
  kalima/kalima/notification/incoming_document/incoming_document.md
  kalima/kalima/notification/incoming_document/incoming_document.py
  kalima/kalima/notification/incoming_document___{{_doc.name_}}/__init__.py
  kalima/kalima/notification/incoming_document___{{_doc.name_}}/incoming_document___{{_doc.name_}}.json
  kalima/kalima/notification/incoming_document___{{_doc.name_}}/incoming_document___{{_doc.name_}}.md
  kalima/kalima/notification/incoming_document___{{_doc.name_}}/incoming_document___{{_doc.name_}}.py
Labels: size/M
