Repository osama1998H/kalima, pull requests merged in 2024-08, with the labels that each got.

#60 hot fixes
  kalima/kalima/doctype/activity_announcement/activity_announcement.json
  kalima/kalima/doctype/activity_request/activity_request.js
  kalima/kalima/doctype/activity_request/activity_request.json
  kalima/kalima/doctype/department_module/department_module.json
  kalima/kalima/doctype/lend_book/lend_book.js
  kalima/kalima/doctype/lend_book/lend_book.json
  kalima/kalima/doctype/presented_module/presented_module.json
  kalima/kalima/doctype/student/student.py
  kalima/kalima/page/master_sheet/master_sheet.py
  kalima/kalima/page/student_portal/student_portal.js
  kalima/utils/utils.py
Labels: size/L

#61 tags
  kalima/kalima/doctype/book/book.json
  kalima/kalima/doctype/book/book.py
  kalima/kalima/doctype/lend_book/lend_book.py
  kalima/utils/utils.py
Labels: size/S

#62 Develop
  kalima/kalima/doctype/activity_announcement/activity_announcement.json
  kalima/kalima/doctype/activity_request/activity_request.js
  kalima/kalima/doctype/activity_request/activity_request.json
  kalima/kalima/doctype/book/book.json
  kalima/kalima/doctype/book/book.py
  kalima/kalima/doctype/department_module/department_module.json
  kalima/kalima/doctype/lend_book/lend_book.js
  kalima/kalima/doctype/lend_book/lend_book.json
  kalima/kalima/doctype/lend_book/lend_book.py
  kalima/kalima/doctype/presented_module/presented_module.json
  kalima/kalima/doctype/student/student.py
  kalima/kalima/page/master_sheet/master_sheet.py
  kalima/kalima/page/student_portal/student_portal.js
  kalima/utils/utils.py
Labels: size/L

#65 annual sheet
  kalima/kalima/custom/department.json
  kalima/kalima/doctype/applicant_student/applicant_student.py
  kalima/kalima/doctype/student_result_log/student_result_log.json
  kalima/kalima/page/annual_students_resu/annual_students_resu.js
  kalima/kalima/page/courses_students_res/courses_students_res.js
  kalima/kalima/page/student_result_entry/student_result_entry.js
  kalima/kalima/workspace/continuing_education/continuing_education.json
  kalima/kalima/workspace/dean's_secretariat/dean's_secretariat.json
  kalima/kalima/workspace/departments/departments.json
  kalima/kalima/workspace/legal_department/legal_department.json
  kalima/kalima/workspace/managment/managment.json
  kalima/kalima/workspace/registration_office/registration_office.json
  kalima/utils/__init__.py
  kalima/utils/annual_sheet.py
  kalima/utils/utils.py
Labels: size/XXL

#66 Develop
  kalima/kalima/custom/department.json
  kalima/kalima/doctype/applicant_student/applicant_student.py
  kalima/kalima/doctype/student_result_log/student_result_log.json
  kalima/kalima/page/annual_students_resu/annual_students_resu.js
  kalima/kalima/page/courses_students_res/courses_students_res.js
  kalima/kalima/page/student_result_entry/student_result_entry.js
  kalima/kalima/workspace/continuing_education/continuing_education.json
  kalima/kalima/workspace/dean's_secretariat/dean's_secretariat.json
  kalima/kalima/workspace/departments/departments.json
  kalima/kalima/workspace/legal_department/legal_department.json
  kalima/kalima/workspace/managment/managment.json
  kalima/kalima/workspace/registration_office/registration_office.json
  kalima/utils/__init__.py
  kalima/utils/annual_sheet.py
  kalima/utils/utils.py
Labels: size/XXL

#67 applicant fix
  kalima/kalima/doctype/applicant_student/applicant_student.py
Labels: size/S

#68 Develop
  kalima/kalima/doctype/applicant_student/applicant_student.py
Labels: size/S

#69 3 Fixes
  kalima/kalima/doctype/class_continuous_exam/class_continuous_exam.js
  kalima/kalima/doctype/master_sheet_data/__init__.py
  kalima/kalima/doctype/master_sheet_data/master_sheet_data.js
  kalima/kalima/doctype/master_sheet_data/master_sheet_data.json
  kalima/kalima/doctype/master_sheet_data/master_sheet_data.py
  kalima/kalima/doctype/master_sheet_data/test_master_sheet_data.py
  kalima/kalima/page/courses_students_res/courses_students_res.js
  kalima/kalima/page/master_sheet/master_sheet.js
  kalima/kalima/page/master_sheet/master_sheet.py
  kalima/kalima/page/student_result_entry/student_result_entry.js
  kalima/kalima/workspace/departments/departments.json
  kalima/utils/utils.py
Labels: size/L

#70 Part 4
  kalima/kalima/doctype/class/class.json
  kalima/kalima/page/class_distribution_t/class_distribution_t.js
  kalima/utils/group_class.py
Labels: size/L

#71 Develop
  kalima/kalima/doctype/class/class.json
  kalima/kalima/doctype/class_continuous_exam/class_continuous_exam.js
  kalima/kalima/doctype/master_sheet_data/__init__.py
  kalima/kalima/doctype/master_sheet_data/master_sheet_data.js
  kalima/kalima/doctype/master_sheet_data/master_sheet_data.json
  kalima/kalima/doctype/master_sheet_data/master_sheet_data.py
  kalima/kalima/doctype/master_sheet_data/test_master_sheet_data.py
  kalima/kalima/page/class_distribution_t/class_distribution_t.js
  kalima/kalima/page/courses_students_res/courses_students_res.js
  kalima/kalima/page/master_sheet/master_sheet.js
  kalima/kalima/page/master_sheet/master_sheet.py
  kalima/kalima/page/student_result_entry/student_result_entry.js
  kalima/kalima/workspace/departments/departments.json
  kalima/utils/group_class.py
  kalima/utils/utils.py
Labels: size/XL

#74 Part 4
  kalima/kalima/doctype/class_continuous_exam/class_continuous_exam.json
  kalima/kalima/page/annual_students_resu/annual_students_resu.js
  kalima/kalima/page/class_distribution_t/class_distribution_t.js
  kalima/kalima/page/class_managment/class_managment.js
  kalima/kalima/page/courses_students_res/courses_students_res.js
  kalima/kalima/page/master_sheet/master_sheet.js
  kalima/kalima/page/student_portal/student_portal.js
  kalima/kalima/page/student_result_entry/student_result_entry.js
  kalima/kalima/page/student_result_sheet_1/student_result_sheet_1.js
  kalima/utils/annual_sheet.py
  kalima/utils/group_class.py
  kalima/utils/utils.py
Labels: size/XXL

#75 Develop
  kalima/kalima/doctype/class_continuous_exam/class_continuous_exam.json
  kalima/kalima/page/annual_students_resu/annual_students_resu.js
  kalima/kalima/page/class_distribution_t/class_distribution_t.js
  kalima/kalima/page/class_managment/class_managment.js
  kalima/kalima/page/courses_students_res/courses_students_res.js
  kalima/kalima/page/master_sheet/master_sheet.js
  kalima/kalima/page/student_portal/student_portal.js
  kalima/kalima/page/student_result_entry/student_result_entry.js
  kalima/kalima/page/student_result_sheet_1/student_result_sheet_1.js
  kalima/utils/annual_sheet.py
  kalima/utils/group_class.py
  kalima/utils/utils.py
Labels: size/XXL

#76 some fixes
  kalima/kalima/doctype/activity/activity.json
  kalima/kalima/doctype/activity/activity.py
  kalima/kalima/doctype/general_participants/general_participants.json
  kalima/kalima/doctype/week_days/week_days.json
  kalima/utils/utils.py
Labels: size/M

#77 Develop
  kalima/kalima/doctype/activity/activity.json
  kalima/kalima/doctype/activity/activity.py
  kalima/kalima/doctype/general_participants/general_participants.json
  kalima/kalima/doctype/week_days/week_days.json
  kalima/utils/utils.py
Labels: size/M

#79 August end testing
  kalima/fixtures/letter_head.json
  kalima/fixtures/week_day.json
  kalima/hooks.py
  kalima/kalima/doctype/activity/activity.json
  kalima/kalima/doctype/addon_fees/__init__.py
  kalima/kalima/doctype/addon_fees/addon_fees.json
  kalima/kalima/doctype/addon_fees/addon_fees.py
  kalima/kalima/doctype/applicant_student/applicant_student.json
  kalima/kalima/doctype/applicant_student/applicant_student.py
  kalima/kalima/doctype/class_timetable/class_timetable.json
  kalima/kalima/doctype/exam_hall_distribution/exam_hall_distribution.py
  kalima/kalima/doctype/student/student.json
  kalima/kalima/doctype/student/student.py
  kalima/kalima/doctype/students_fees/students_fees.js
  kalima/kalima/doctype/students_fees/students_fees.json
  kalima/kalima/doctype/students_fees/students_fees.py
  kalima/kalima/doctype/week_days/week_days.json
  kalima/kalima/page/student_portal/student_portal.js
  kalima/modules.txt
  kalima/public/css/2.ttf
  kalima/public/css/image_2024-08-25_14-03-21.png
  kalima/utils/group_class.py
  kalima/utils/utils.py
Labels: size/L

#80 Develop
  kalima/fixtures/letter_head.json
  kalima/fixtures/week_day.json
  kalima/hooks.py
  kalima/kalima/doctype/activity/activity.json
  kalima/kalima/doctype/addon_fees/__init__.py
  kalima/kalima/doctype/addon_fees/addon_fees.json
  kalima/kalima/doctype/addon_fees/addon_fees.py
  kalima/kalima/doctype/applicant_student/applicant_student.json
  kalima/kalima/doctype/applicant_student/applicant_student.py
  kalima/kalima/doctype/class_timetable/class_timetable.json
  kalima/kalima/doctype/exam_hall_distribution/exam_hall_distribution.py
  kalima/kalima/doctype/student/student.json
  kalima/kalima/doctype/student/student.py
  kalima/kalima/doctype/students_fees/students_fees.js
  kalima/kalima/doctype/students_fees/students_fees.json
  kalima/kalima/doctype/students_fees/students_fees.py
  kalima/kalima/doctype/week_days/week_days.json
  kalima/kalima/page/student_portal/student_portal.js
  kalima/modules.txt
  kalima/public/css/2.ttf
  kalima/public/css/image_2024-08-25_14-03-21.png
  kalima/utils/group_class.py
  kalima/utils/utils.py
Labels: size/L

#81 Document Department + print format
  kalima/kalima/doctype/academic_semester/academic_semester.json
  kalima/kalima/doctype/activity/activity.json
  kalima/kalima/doctype/activity_announcement/activity_announcement.json
  kalima/kalima/doctype/activity_certificate/activity_certificate.json
  kalima/kalima/doctype/activity_coordination/activity_coordination.json
  kalima/kalima/doctype/activity_request/activity_request.json
  kalima/kalima/doctype/applicant_student/applicant_student.json
  kalima/kalima/doctype/book/book.json
  kalima/kalima/doctype/book_category/book_category.json
  kalima/kalima/doctype/borrowing_limitations/borrowing_limitations.json
  kalima/kalima/doctype/class/class.json
  kalima/kalima/doctype/class_continuous_exam/class_continuous_exam.json
  kalima/kalima/doctype/class_session/class_session.json
  kalima/kalima/doctype/class_timetable/class_timetable.json
  kalima/kalima/doctype/classroom/classroom.json
  kalima/kalima/doctype/complaints/complaints.json
  kalima/kalima/doctype/constant/constant.json
  kalima/kalima/doctype/department_module/department_module.json
  kalima/kalima/doctype/dormitory/dormitory.json
  kalima/kalima/doctype/exam_hall_distribution/exam_hall_distribution.json
  kalima/kalima/doctype/exam_questions/exam_questions.json
  kalima/kalima/doctype/exam_result_entry/exam_result_entry.json
  kalima/kalima/doctype/exam_schedule/exam_schedule.json
  kalima/kalima/doctype/faculty/faculty.json
  kalima/kalima/doctype/fines/fines.json
  kalima/kalima/doctype/hostel/hostel.json
  kalima/kalima/doctype/incoming/incoming.json
  kalima/kalima/doctype/lend_book/lend_book.json
  kalima/kalima/doctype/library/library.json
  kalima/kalima/doctype/outgoing/outgoing.json
  kalima/kalima/doctype/question_prototype/question_prototype.json
  kalima/kalima/doctype/research/research.json
  kalima/kalima/doctype/student/student.json
  kalima/kalima/doctype/student_attendance_entry/student_attendance_entry.json
  kalima/kalima/doctype/student_exam_result/student_exam_result.json
  kalima/kalima/doctype/student_fee_structure/student_fee_structure.json
  kalima/kalima/doctype/student_result_log/student_result_log.json
  kalima/kalima/doctype/students_fees/students_fees.json
  kalima/kalima/doctype/transfer/transfer.json
Labels: size/L

#82 Develop
  kalima/kalima/doctype/academic_semester/academic_semester.json
  kalima/kalima/doctype/activity/activity.json
  kalima/kalima/doctype/activity_announcement/activity_announcement.json
  kalima/kalima/doctype/activity_certificate/activity_certificate.json
  kalima/kalima/doctype/activity_coordination/activity_coordination.json
  kalima/kalima/doctype/activity_request/activity_request.json
  kalima/kalima/doctype/applicant_student/applicant_student.json
  kalima/kalima/doctype/book/book.json
  kalima/kalima/doctype/book_category/book_category.json
  kalima/kalima/doctype/borrowing_limitations/borrowing_limitations.json
  kalima/kalima/doctype/class/class.json
  kalima/kalima/doctype/class_continuous_exam/class_continuous_exam.json
  kalima/kalima/doctype/class_session/class_session.json
  kalima/kalima/doctype/class_timetable/class_timetable.json
  kalima/kalima/doctype/classroom/classroom.json
  kalima/kalima/doctype/complaints/complaints.json
  kalima/kalima/doctype/constant/constant.json
  kalima/kalima/doctype/department_module/department_module.json
  kalima/kalima/doctype/dormitory/dormitory.json
  kalima/kalima/doctype/exam_hall_distribution/exam_hall_distribution.json
  kalima/kalima/doctype/exam_questions/exam_questions.json
  kalima/kalima/doctype/exam_result_entry/exam_result_entry.json
  kalima/kalima/doctype/exam_schedule/exam_schedule.json
  kalima/kalima/doctype/faculty/faculty.json
  kalima/kalima/doctype/fines/fines.json
  kalima/kalima/doctype/hostel/hostel.json
  kalima/kalima/doctype/incoming/incoming.json
  kalima/kalima/doctype/lend_book/lend_book.json
  kalima/kalima/doctype/library/library.json
  kalima/kalima/doctype/outgoing/outgoing.json
  kalima/kalima/doctype/question_prototype/question_prototype.json
  kalima/kalima/doctype/research/research.json
  kalima/kalima/doctype/student/student.json
  kalima/kalima/doctype/student_attendance_entry/student_attendance_entry.json
  kalima/kalima/doctype/student_exam_result/student_exam_result.json
  kalima/kalima/doctype/student_fee_structure/student_fee_structure.json
  kalima/kalima/doctype/student_result_log/student_result_log.json
  kalima/kalima/doctype/students_fees/students_fees.json
  kalima/kalima/doctype/transfer/transfer.json
Labels: size/L

#83 doctypes change
  kalima/kalima/doctype/incoming/incoming.json
  kalima/kalima/doctype/week_day/week_day.json
Labels: size/XS

#84 Develop
  kalima/kalima/doctype/incoming/incoming.json
  kalima/kalima/doctype/week_day/week_day.json
Labels: size/XS

#86 Hot fixes
  MANIFEST.in
  README.md
  kalima_old.csv
  license.txt
  package.json
  requirements.txt
Labels: size/L

#87 Develop
  MANIFEST.in
  README.md
  kalima_old.csv
  license.txt
  package.json
  requirements.txt
Labels: size/L
